### ISSUE TITLE
Could not find any factory for identifier 'upsert-kafka'   这是少了哪个包??

### ISSUE THREAD

**Issue by ithjz** [fsk119/flink-pageviews-demo#1]
Could not find any factory for identifier 'upsert-kafka'   这是少了哪个包??

Could not find any factory for identifier 'upsert-kafka'   这是少了哪个包??

CREATE TABLE e1 (
  user_id BIGINT,
  user_region STRING,
  page_id BIGINT,
  view_time TIMESTAMP(3),
  WATERMARK FOR view_time as view_time - INTERVAL '5' SECOND,
  PRIMARY KEY (user_id, page_id) NOT ENFORCED
) WITH (
  'connector' = 'upsert-kafka',
  'topic' = 'enriched_pageviews',
  'properties.bootstrap.servers' = 'xxxxxxxxxxxxx',
  'key.format' = 'json',
  'value.format' = 'json'
);

[ERROR] Could not execute SQL statement. Reason:
org.apache.flink.table.api.ValidationException: Could not find any factory for identifier 'upsert-kafka' that implements 'org.apache.flink.table.factories.DynamicTableFactory' in the classpath.

Available factory identifiers are:

blackhole
clickhouse
datagen
filesystem
jdbc
kafka
mysql-cdc
postgres-cdc
print

**Comment by fsk119** [comment]
Hi. 请问是不是从markdown里面下载所需要的包？upsert-kafka是1.12的新特性，如果是1.12编译得到的话 kafka的包应该是足够的。
