### ISSUE TITLE
基于sql_client报错了,  .InvalidClassException: a.FlinkKafkaConsumer??

### ISSUE THREAD

**Issue by ithjz** [fsk119/flink-pageviews-demo#2]
基于sql_client报错了,  .InvalidClassException: a.FlinkKafkaConsumer??

Flink SQL> select  *  from   pageviews;
[ERROR] Could not execute SQL statement. Reason:
java.io.InvalidClassException: org.apache.flink.streaming.connectors.kafka.FlinkKafkaConsumer; local class incompatible: stream classdesc serialVersionUID = 1, local class serialVersionUID = 5680402886573458792

**Comment by fsk119** [comment]
请使用1.12的环境以及相应的包。

**Comment by fsk119** [comment]
Close it.
